

export const tags = [
    { name: "agile", href: "https://testomat.io/tag/agile/" },
    { name: "analytics", href: "https://testomat.io/tag/analytics/" },
    { name: "api testing", href: "https://testomat.io/tag/api-testing/" },
    { name: "automation testing", href: "https://testomat.io/tag/automation-testing/" },
    { name: "bdd", href: "https://testomat.io/tag/bdd/" },
    { name: "ci/cd", href: "https://testomat.io/tag/cicd/" },
    { name: "comparison", href: "https://testomat.io/tag/comparison/" },
    { name: "cucumber", href: "https://testomat.io/tag/cucumber/" },
    { name: "cypress", href: "https://testomat.io/tag/cypress/" },
    { name: "testing framework", href: "https://testomat.io/tag/testing-framework/" },
    { name: "gherkin", href: "https://testomat.io/tag/gherkin/" },
    { name: "insights", href: "https://testomat.io/tag/insights/" },
    { name: "javascript", href: "https://testomat.io/tag/javascript/" },
    { name: "jira", href: "https://testomat.io/tag/jira/" },
    { name: "mobile testing", href: "https://testomat.io/tag/mobile-testing/" },
    { name: "news", href: "https://testomat.io/tag/news/" },
    { name: "playwright", href: "https://testomat.io/tag/playwright/" },
    { name: "python", href: "https://testomat.io/tag/python/" },
    { name: "qa process", href: "https://testomat.io/tag/qa-process/" },
    { name: "review", href: "https://testomat.io/tag/review/" },
    { name: "test management", href: "https://testomat.io/tag/test-management/" },
    { name: "test reports", href: "https://testomat.io/tag/test-reports/" },
    { name: "testing as a service", href: "https://testomat.io/tag/testing-as-a-service/" },
    { name: "testing tool", href: "https://testomat.io/tag/testing-tool/" },
    { name: "testing types", href: "https://testomat.io/tag/testing-types/" },
    { name: "video", href: "https://testomat.io/tag/video/" },
];
